rework template
subsquid/squid-template pull request #43
Opened 2022-07-30 13:19 UTC by belopash

2022-07-30 14:52 UTC, dzhelezov requested changes

2022-07-30 14:52 UTC, dzhelezov commented on schema.graphql
> +  amount: BigInt!
Add index here to filter big transfers

2022-07-30 14:52 UTC, dzhelezov commented on schema.graphql
> +  fee: BigInt
Should make the fee non-nullable and zero by default?

2022-07-30 14:52 UTC, dzhelezov commented on schema.graphql
> +  extrinsic: String @index
txHash or extrinsicHash is a better name

2022-07-30 15:46 UTC, belopash commented on schema.graphql
> +  fee: BigInt
Not sure about that. We can't calculate fee for some old extrinsics. So null fee is like "fee is not defined".

2022-07-30 15:47 UTC, belopash commented on schema.graphql
> +  extrinsic: String @index
I think extrinsicHash will be better. txHash we use with evm.

2022-08-01 07:31 UTC, dzhelezov commented on schema.graphql
> +  extrinsic: String @index
Ok let's do `extrinsicHash`!

2022-08-01 07:33 UTC, dzhelezov commented on schema.graphql
> +  fee: BigInt
I think it complicates things for the API clients, so we can just set zero by default for this template (and add a field along the lines`The fee is calculated at the best effort and may be zero for some old extrinsics`).

2022-08-01 08:32 UTC, dzhelezov approved these changes
LGTM modulo the small changes in the comments

2022-08-01 12:00 UTC, merged